### PR TITLE
Fixes #80 - moved theme switching logic to separate component

### LINKED ISSUE #80: Extract out theme switcher logic into seperate component

### PR DESCRIPTION
**Pull request by m0mosenpai**
Fixes #80 
- [X] Move logic to new component
- [X] Use theme switcher in the header
- [x] Test everything
- [x] Squash commits

### CODE REVIEW

**Comment by m0mosenpai** [comment]
The component renders now. There's another small issue though. The logo doesn't change color when I switch themes. If I login with the light theme, the logo will be dark by default. Changing to dark theme with the toggle button will not make it switch to light version of the logo.
And when I login with the dark theme, logo will be light bey default but will not change to dark with the toggle button.

I'm guessing `isDarkTheme` is not being read everytime the button is clicked or something. It works correctly in the demo and it worked correctly before these changes so its something related to this only.

**Comment by Eshaan7** [comment]
Might have to use this https://akveo.github.io/nebular/docs/services/themeservice#nbthemeservice: `onThemeChange()` to subscribe to theme value so it gets updated on every change.

**Comment by m0mosenpai** [comment]
I'll work on the navbar logo part in a separate PR. Let me know what needs to be done there.

**Comment by Eshaan7** [comment]
Is the work in this PR final ?

**Comment by m0mosenpai** [comment]
> Is the work in this PR final ?

Yes. Unless there are any other changes required? I implemented onThemeChange() and tested everything out.

**Comment by Eshaan7** [comment]
Thanks for your patience. Just made a small fix.

**Pull request merged**
